# Generated by Django 5.2.17 on 2026-08-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_reprice_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_text', models.CharField(blank=True, max_length=180)),
                ('image', models.FileField(blank=True, upload_to='showcase/cards/')),
                ('image_url', models.URLField(blank=True, help_text='Optional alternative to an uploaded image.')),
                ('destination_url', models.URLField(help_text='Website, WhatsApp, form or portal link.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PubliFuerteventura', max_length=80)),
                ('intro', models.TextField(default='Everything happening in Fuerteventura, in one place. Discover our portals, projects and people — then connect directly.', max_length=280)),
                ('hero_title', models.CharField(default='Fuerteventura, all connected.', max_length=120)),
                ('hero_image', models.FileField(blank=True, upload_to='showcase/')),
                ('hero_image_url', models.URLField(blank=True, help_text='Optional alternative to an uploaded image.')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube, Vimeo or another external trailer link.')),
                ('contact_url', models.URLField(blank=True, default='https://wa.me/')),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='showcase/sponsors/')),
                ('image_url', models.URLField(blank=True, help_text='Optional alternative to an uploaded image.')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=160)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('image', models.FileField(blank=True, upload_to='showcase/team/')),
                ('image_url', models.URLField(blank=True, help_text='Optional alternative to an uploaded image.')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
