# Generated by Django 5.2.17 on 2026-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_seed_network_portals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasecard',
            name='destination_url',
            field=models.URLField(blank=True, help_text='Website, WhatsApp, form or portal link. Leave blank to show a non-clickable card.'),
        ),
    ]
