# Generated by Django 5.2.17 on 2026-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_remote_escape_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, help_text='Direct website or booking link.'),
        ),
    ]
