# Generated by Django 5.2.17 on 2026-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_feature_selected_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='team_eyebrow',
            field=models.CharField(default='WHO WE ARE', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_intro',
            field=models.TextField(default='A local, creative network connecting ideas, projects and people across Fuerteventura.', max_length=320),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_title',
            field=models.CharField(default='People making connections happen.', max_length=160),
        ),
    ]
