# Generated by Django 5.2.17 on 2026-08-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_business_logos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
    ]
