# Generated by Django 5.2.17 on 2026-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_alter_sponsor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the collaborations page.', max_length=300),
        ),
    ]
