# Generated by Django 5.2.17 on 2026-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='businesses/covers/'),
        ),
        migrations.AddField(
            model_name='business',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Optional external cover image URL.'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.FileField(blank=True, upload_to='businesses/logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Optional external logo URL.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_url',
            field=models.URLField(blank=True, help_text='Existing logo fallback. Prefer the dedicated logo fields below.', verbose_name='legacy logo URL'),
        ),
    ]
