# Generated by Django 5.2.17 on 2026-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_business_cover_image_business_cover_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Analytics page view',
                'verbose_name_plural': 'Analytics',
                'ordering': ('-created_at',),
            },
        ),
    ]
